$VM_BOX = ENV.has_key?('VM_BOX') ? ENV['VM_BOX'] : 'hashicorp/precise32'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = $VM_BOX

    config.vm.provision :ansible do |ansible|
        ansible.playbook = 'test.yml'
        ansible.extra_vars = { ansible_ssh_user: 'vagrant', vagrant: true }
        ansible.verbose = 'vv'
    end
end
